import {useEffect,useState} from 'react';import{invoke}from'@tauri-apps/api/core';
type Detail={threadId:string;phase:string;repository?:string|null;currentTurnId?:string|null;currentTurnStatus?:string|null;turnStartedAt?:number|null;turnEndedAt?:number|null;modelContextWindow?:number|null;collaborationMode?:string|null;runtimeType?:string|null;runtimeFlags?:string[];metadataSource?:string;nextRecoveryCheckAt?:number;quotaAttribution?:{status:string;reason:string};policy:{nextAttemptAt?:number}};
const time=(value:number|null|undefined)=>value?new Date(value).toLocaleString():'Unavailable: turn timestamp was not exposed';
export default function ThreadDetails({task,privacy}:{task:Detail;privacy:boolean}){
 const[analytics,setAnalytics]=useState<{groups:Array<{key:unknown;ledger:string;tokens:Record<string,number|null>;samples:number;tokenTotalStatus:string}>}|null>(null),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false);
 const elapsed=task.turnStartedAt&&task.currentTurnStatus==='inProgress'?`${Math.floor(Math.max(0,Date.now()-task.turnStartedAt)/1000)}s`:'Unavailable: no active turn start timestamp';
 useEffect(()=>{if(!open)return;invoke<typeof analytics>('core_request',{method:'analytics/summary',params:{groupBy:'thread'}}).then(value=>{if(value)setAnalytics({...value,groups:value.groups.filter(g=>g.key===task.threadId)});}).catch(e=>setError(String(e)));},[task.threadId,open]);
 return <details className="thread-details" onToggle={event=>setOpen(event.currentTarget.open)}><summary>Observed details & token ledgers</summary><div className="diagnostic-grid">{Object.entries({Repository:privacy?'Hidden in privacy mode':task.repository??'Unavailable: verified snapshot did not expose repository metadata',CurrentTurn:privacy?'Hidden in privacy mode':task.currentTurnId??'Unavailable: latest canonical turn missing',TurnStatus:task.currentTurnStatus??'Unavailable',StartedAt:time(task.turnStartedAt),EndedAt:time(task.turnEndedAt),RunningDuration:elapsed,CollaborationMode:task.collaborationMode??'Unavailable: turn mode not exposed',ContextCapacity:task.modelContextWindow==null?'Unavailable: configured capacity not exposed':`${task.modelContextWindow.toLocaleString()} tokens (capacity, not actual input)`,Runtime:task.runtimeType??'Unavailable',RuntimeFlags:task.runtimeFlags?.join(', ')||'No active runtime flags reported',NextQuotaCheck:task.phase==='waitingQuota'?time(task.nextRecoveryCheckAt):'Not waiting for quota',RetryCooldown:task.policy.nextAttemptAt?time(task.policy.nextAttemptAt):'None',QuotaImpact:`${task.quotaAttribution?.status??'Unavailable'}: ${task.quotaAttribution?.reason??'No reliable per-thread subscription attribution'}`,Source:task.metadataSource??'Verified Desktop snapshot',HungDetection:'Unavailable: no authoritative inactivity timing exposed'}).map(([key,value])=><div key={key}><small>{key}</small><strong>{value}</strong></div>)}</div><h3>Observed token ledgers</h3>{error?<p className="error">{error}</p>:analytics?<>{analytics.groups.length?analytics.groups.map(g=><p className="caption" key={g.ledger}>{g.ledger}: {g.tokens.total_tokens==null?'Unavailable':g.tokens.total_tokens.toLocaleString()} observed total tokens · {g.samples} records · {g.tokenTotalStatus}</p>):<p className="caption">Unavailable: no matching local token ledger yet.</p>}<p className="caption">Response, cumulative deltas and historical inventories overlap. They are never combined into a fake thread consumption total.</p></>:<p className="caption">Loading local token observations…</p>}</details>;
}
